# Generated by Django 2.2.5 on 2019-11-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
