# Generated by Django 2.2.5 on 2019-11-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
