# Generated by Django 2.2.5 on 2019-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191118_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_body',
            field=models.TextField(),
        ),
    ]
